---
services:
  pwr_stat:
    container_name: pwr_stat
    hostname: pwr_stat
    restart: unless-stopped
    image: dwinks/pwrstat_docker:latest
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/ups:/dev/ups
    volumes:
      - ./pwrstat.yaml:/pwrstat.yaml:ro
      # Optionally override the powerstatd configuration file
      - ./pwrstatd.conf:/etc/pwrstatd.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:5002/pwrstat"]
      interval: 30s
      timeout: 1s
      retries: 24
    ports:
      - 5002:5002 # API
